#!/bin/bash
alias myssh="/usr/bin/ssh"
alias git=$(which git)
alias git-cvsserver=$(which git-cvsserver)
alias git-flow=$(which git-flow)
alias git-receive-pack=$(which git-receive-pack)
alias git-shell=$(which git-shell)
alias git-upload-archive=$(which git-upload-archive)
alias git-upload-pack=$(which git-upload-pack)
alias gitk=$(which gitk)
alias gitx=$(which gitx)
alias ls='ls -FCG'
alias webserver="python -m SimpleHTTPServer"
# Start privoxy that i installed via macports
alias privoxy="sudo launchctl unload /Library/LaunchDaemons/org.macports.Privoxy.plist; \
           sleep 2; sudo launchctl load /Library/LaunchDaemons/org.macports.Privoxy.plist"

